controller_manager:
  ros__parameters:
    update_rate: 400
    # use_sim_time: false
    use_sim_time: true

    arm_cont:
      type: effort_controllers/JointGroupEffortController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      
arm_cont:
  ros__parameters:
    joints:
      - arm_joint